// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc5FFY6sAHvlX-p6snzKZs9mx9aTGwHz4',
    appId: '1:760339693307:web:71b92ea6e5b4ad45a9fa5e',
    messagingSenderId: '760339693307',
    projectId: 'to-do-list-430db',
    authDomain: 'to-do-list-430db.firebaseapp.com',
    storageBucket: 'to-do-list-430db.appspot.com',
    measurementId: 'G-DVKJFBG2ZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlM-944gYVOldnGcZnhSqdw2IOCbR6Xns',
    appId: '1:760339693307:android:8f2ccc302144983da9fa5e',
    messagingSenderId: '760339693307',
    projectId: 'to-do-list-430db',
    storageBucket: 'to-do-list-430db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChr4qOrR0j6PdI2d23A7gCFv6H4n7TEQE',
    appId: '1:760339693307:ios:c5e5762732c6881fa9fa5e',
    messagingSenderId: '760339693307',
    projectId: 'to-do-list-430db',
    storageBucket: 'to-do-list-430db.appspot.com',
    iosBundleId: 'com.example.baseTodolist',
  );
}
